from homeassistant.components.climate import HVACMode, PRESET_HOME

DOMAIN = "comelit"
HUB_DOMAIN = "comelit.hub"
VEDO_DOMAIN = "comelit.vedo"
CONF_MQTT_USER = "mqtt-user"
CONF_MQTT_PASSWORD = "mqtt-password"
CONF_SERIAL = "serial"
CONF_CLIENT = "client"
COVER_CLOSING_TIME = 30  # TODO config

# Base modes
CONST_MODE_OFF = "OFF"
CONST_MODE_SMART_SCHEDULE = "SMART_SCHEDULE"  # Use the schedule
CONST_MODE_AUTO = "AUTO"
CONST_MODE_COOL = "COOL"
CONST_MODE_HEAT = "HEAT"
CONST_MODE_DRY = "DRY"


HA_TO_HVAC_MODE_MAP = {
    HVACMode.OFF: CONST_MODE_OFF,
    HVACMode.HEAT_COOL: CONST_MODE_AUTO,
    HVACMode.AUTO: CONST_MODE_SMART_SCHEDULE,
    HVACMode.HEAT: CONST_MODE_HEAT,
    HVACMode.COOL: CONST_MODE_COOL,
    HVACMode.DRY: CONST_MODE_DRY,
}

TO_HA_HVAC_MODE_MAP = {value: key for key, value in HA_TO_HVAC_MODE_MAP.items()}

SUPPORT_PRESET = [PRESET_HOME]
